server:
  port: 18080

spring:
  application:
    name: campus-ai-assistant
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
